### PR TITLE
Fix/icbm 277

### LINKED ISSUE #277: EMP tower wont switch to Disrupt missiles.
As the title says, for whatever reason, every time i click missiles in the EMP tower it just goes back to electronics.

### PR DESCRIPTION
**Pull request by GHXX**
This fixes #277

### CODE REVIEW

File: src/main/java/icbm/classic/content/reg/ExplosiveInit.java [hunk 1]
```diff
@@ -161,7 +161,7 @@ public static void init()
 
 
         ExplosiveRefs.EMP = newEx(16, "emp", EnumTier.THREE,
-                () -> new BlastEMP().setEffectBlocks().setEffectEntities().setBlastSize(50));
```
Comment (DarkGuardsman) [inline src/main/java/icbm/classic/content/reg/ExplosiveInit.java]: This will break the missile

File: src/main/java/icbm/classic/content/blocks/emptower/TileEMPTower.java [hunk 2]
```diff
@@ -122,7 +123,7 @@ public boolean read(ByteBuf data, int id, EntityPlayer player, IPacket type) //T
                 }
                 case CHANGE_MODE_PACKET_ID:
                 {
-                    empMode = EMPMode.values()[data.readByte()];
```
Comment (DarkGuardsman) [inline src/main/java/icbm/classic/content/blocks/emptower/TileEMPTower.java]: Its written as a byte in the description packet... this will cause it to read over the packet size

Comment (GHXX) [reply src/main/java/icbm/classic/content/blocks/emptower/TileEMPTower.java]: It actually gets written as an integer

**Comment by DarkGuardsman** [comment]
Had to check my notes, EMP mode is slotted for removal
